[project]
name = "nosible-mcp"
version = "0.0.2"
description = "MCP server for the NOSIBLE search API"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.13.1",
    "nosible>=0.3.2",
]
