[project]
name = "nosible-mcp"
version = "0.0.7"
description = "MCP server for the NOSIBLE Search API"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.116.1",
    "httpx>=0.28.1",
    "mcp[cli]>=1.13.1",
    "nosible>=0.3.4",
]
